### ISSUE TITLE
微信自定义转发，在开发者工具中可以正常转发。但是真机只能转发链接

### ISSUE THREAD

**Issue by lmxyjy** [lmxyjy/blogs#41]
**如下所示：**

**真机：**

![1640842826(1)](https://user-images.githubusercontent.com/48620706/147724689-b4d55ebc-8c16-4116-82b5-38ec38cf66a1.png)

**开发者工具：**

![image](https://user-images.githubusercontent.com/48620706/147724561-7437bb4b-ee55-4f38-9eb9-7ead7c94850b.png)

**出现此问题的原因：**

直接通过链接点进去进行转发，微信是不允许的。必须通过二维码等扫码进入。或者通过公众号入口进入的项目才行。

**Comment by gaoqiang19514** [comment]
原来如此，官方文档上好像没有提及此事？如果没有，那可真的太过分了
